/**
 * Database types for Supabase
 * These will be auto-generated by Supabase CLI in production
 * For now, we define them manually based on our schema
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          email: string;
          avatar_url: string | null;
          plan: "free" | "pro";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          email: string;
          avatar_url?: string | null;
          plan?: "free" | "pro";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          email?: string;
          avatar_url?: string | null;
          plan?: "free" | "pro";
          updated_at?: string;
        };
      };
      pages: {
        Row: {
          id: string;
          user_id: string;
          slug: string;
          title: string;
          bio: string | null;
          avatar_url: string | null;
          theme_id: string;
          custom_styles: Json | null;
          seo_title: string | null;
          seo_description: string | null;
          og_image_url: string | null;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          slug: string;
          title: string;
          bio?: string | null;
          avatar_url?: string | null;
          theme_id?: string;
          custom_styles?: Json | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          slug?: string;
          title?: string;
          bio?: string | null;
          avatar_url?: string | null;
          theme_id?: string;
          custom_styles?: Json | null;
          seo_title?: string | null;
          seo_description?: string | null;
          og_image_url?: string | null;
          is_published?: boolean;
          updated_at?: string;
        };
      };
      links: {
        Row: {
          id: string;
          page_id: string;
          title: string;
          url: string;
          icon_url: string | null;
          thumbnail_url: string | null;
          position: number;
          is_active: boolean;
          scheduled_start: string | null;
          scheduled_end: string | null;
          click_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          page_id: string;
          title: string;
          url: string;
          icon_url?: string | null;
          thumbnail_url?: string | null;
          position?: number;
          is_active?: boolean;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          click_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          url?: string;
          icon_url?: string | null;
          thumbnail_url?: string | null;
          position?: number;
          is_active?: boolean;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          click_count?: number;
          updated_at?: string;
        };
      };
      page_views: {
        Row: {
          id: string;
          page_id: string;
          visitor_id: string;
          referrer: string | null;
          country: string | null;
          device: string;
          browser: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          page_id: string;
          visitor_id: string;
          referrer?: string | null;
          country?: string | null;
          device: string;
          browser?: string | null;
          timestamp?: string;
        };
        Update: never;
      };
      link_clicks: {
        Row: {
          id: string;
          link_id: string;
          visitor_id: string;
          referrer: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          link_id: string;
          visitor_id: string;
          referrer?: string | null;
          timestamp?: string;
        };
        Update: never;
      };
    };
  };
}

